In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [100]:
from sklearn.preprocessing import LabelEncoder

In [101]:
#(this function returns prior probability)
def prior_prob(y,label):
    numerator = np.sum(y==label)
    denominator = y.shape[0]
    return numerator/float(denominator)

#(this function returns the conditional probability)
def cond_prob(x ,y,f_col,f_label,label):
    x = x[:,f_col]
    filtered_x   = x[y==label]
    denominator = filtered_x.shape[0]
    numerator = np.sum(filtered_x==f_label)
    
    return numerator/denominator

#(this function returns the predictions)
def predict(x_train,y_train,x_test):
    x_test = x_test.reshape((1,-1))
    m = x_train.shape[0]
    n = x_train.shape[1]
    classes = np.unique(y_train)
    probabilities = []
    for label in classes:
        
        likelihood = 1.0
        for i in range(n):
            conditional = cond_prob(x_train,y_train,i,x_test[0][i],label)
            likelihood *= conditional
        prior = prior_prob(y_train,label)
        
        posterior = likelihood*prior
        probabilities.append(posterior)
        
    return np.argmax(probabilities)
    
def accuracy(y_pred,y_test):
    correct = np.sum(y_pred==y_test)
    total = y_test.shape[0]
    return correct/total  

In [102]:
pwd

'C:\\Users\\Neil\\Desktop'

In [103]:
data = pd.read_csv("Social_Network_Ads.csv")

In [104]:
data.head(n=5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [105]:
le  = LabelEncoder()

In [106]:
print(type(data))
data = np.array(data)
data = data[:,1:]

<class 'pandas.core.frame.DataFrame'>


In [108]:
feature1 = data[:,0]

In [109]:
feature1 = le.fit_transform(feature1)

In [37]:
data = data[:,1:]
data = np.c_[feature1,data]

In [42]:
data

array([[1, 19, 19000, 0],
       [1, 35, 20000, 0],
       [0, 26, 43000, 0],
       ...,
       [0, 50, 20000, 1],
       [1, 36, 33000, 0],
       [0, 49, 36000, 1]], dtype=object)

In [43]:
x = data[:,:-1]
y = data[:,-1]

In [44]:
print(x)
print(y)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [71]:
x_train = x[:300,:]
x_test = x[300:,:]
y_train  = y[:300]
y_test = y[300:]
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(300, 3)
(300,)
(100, 3)
(100,)


In [73]:
y_pred = list()
for i in range(x_test.shape[0]):
    pred = predict(x_train,y_train,x_test[i])
    y_pred.append(pred)dd
    
print(y_pred)
print(y_test)
print(accuracy(np.array(y_pred),y_test))

[1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1]
[1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1
 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1
 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]
0.61
